<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageVersion Include="Concentus" Version="2.2.2" />
    <PackageVersion Include="Concentus.Oggfile" Version="1.0.7" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="H.NotifyIcon.Maui" Version="2.4.1" />
    <PackageVersion Include="JAJ.Packages.MiniAudioEx" Version="3.3.5" />
    <PackageVersion Include="KokoroSharp.CPU" Version="0.8.0" />
    <PackageVersion Include="Markdig" Version="1.3.2" />
    <PackageVersion Include="Microsoft.Data.Sqlite.Core" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Maui.Controls" Version="10.0.20" />
    <PackageVersion Include="Microsoft.Maui.Platforms.Linux.Gtk4" Version="0.1.0-preview.12.26368.2" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="NAudio" Version="2.3.0" />
    <PackageVersion Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.5" />
    <PackageVersion Include="SQLitePCLRaw.provider.dynamic_cdecl" Version="3.0.5" />
    <PackageVersion Include="System.Security.Cryptography.ProtectedData" Version="10.0.10" />
    <PackageVersion Include="Tmds.DBus.Protocol" Version="0.94.2" />
    <PackageVersion Include="Tmds.DBus.Generator" Version="0.94.2" />
    <PackageVersion Include="Whisper.net" Version="1.9.1" />
    <PackageVersion Include="Whisper.net.Runtime" Version="1.9.1" />
    <PackageVersion Include="Whisper.net.Runtime.Cuda.Windows" Version="1.9.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
</Project>
