<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Concentus" />
    <PackageReference Include="Concentus.Oggfile" />
    <PackageReference Include="NAudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Buddy.Core\Buddy.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Buddy.IntegrationTests" />
  </ItemGroup>
</Project>
